name: device_frame
description: Mockups for common devices.
version: 0.3.0
homepage: https://github.com/aloisdeniel/flutter_device_preview
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_svg: ^0.21.0-nullsafety.0
  path_drawing: ^0.5.0-nullsafety.0
  freezed_annotation: ^0.14.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^4.0.0
  freezed: ^0.14.1
  xml: ^5.0.0