name: device_frame
description: Mockups for common devices.
version: 0.3.0
homepage: https://github.com/aloisdeniel/flutter_device_preview
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_svg: ^0.22.0
  path_drawing: ^0.5.1
  freezed_annotation: ^0.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: 3.5.1 # Last version without required null safety
  freezed: ^0.12.7
  xml: ^5.1.1