name: device_preview
version: 0.6.2-beta-brance
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview
publish_to: none

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.2.4
  shared_preferences: ^2.0.5
  shared_preferences_macos: ^2.0.0
  provider: ^4.0.5
  path_provider: ^2.0.1
  device_frame: 
    path: ../device_frame
  font_awesome_flutter: ^8.9.0
  http: ^0.13.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.0
  path: ^1.8.0-nullsafety.1

dev_dependencies:
  freezed: ^0.14.1
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  analyzer: ">=0.41.0 <2.0.0"
